image: python:3.10-alpine

build:
  stage: build
  only:
    - main
  before_script:
    pip install -r requirements.txt
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  only:
    - main
  needs:
    - job: build
      artifacts: true
  script:
    - true
  artifacts:
    paths:
      - public
