build:
  image: python:3.10-alpine
  stage: build
  only:
    - main
  before_script:
    pip install -r requirements.txt
  script:
    - mkdocs build
  artifacts:
    paths:
      - site

pages:
  stage: deploy
  only:
    - main
  needs:
    - job: build
      artifacts: true
  script:
    - mv site public
  artifacts:
    paths:
      - public
